class CreateIeltsReadingPassages < ActiveRecord::Migration[7.1]
  def change
    create_table :ielts_reading_passages, id: :uuid, default: -> { "gen_random_uuid()" } do |t|
      t.references :user, null: false, foreign_key: true, type: :uuid
      t.string  :title,        null: false
      t.text    :body,         null: false
      # band_5 / band_6 / band_7 / band_8
      t.string  :difficulty,   null: false, default: "band_6"
      # academic / general
      t.string  :passage_type, null: false, default: "academic"
      t.string  :topic
      # Stores array of question objects generated by the AI
      t.jsonb   :questions,    null: false, default: []

      t.timestamps
    end

    add_index :ielts_reading_passages, [:user_id, :created_at]
    add_index :ielts_reading_passages, :difficulty
  end
end
